#!/usr/bin/env python3
"""Regenerates `ru.rs` from the Russian table in Sources/CapacityNotchCore/Localization.swift.

Run from the repository root:  python3 linux/crates/core/src/loc/gen_ru.py
The Swift table is the source of truth; `ru.rs` is generated and not edited by hand.
"""
import re, pathlib

root = pathlib.Path(__file__).resolve().parents[5]
src = (root / "Sources/CapacityNotchCore/Localization.swift").read_text().split("\n")
start = next(i for i, l in enumerate(src) if "public static let russian" in l)
end = next(i for i in range(start, len(src)) if src[i] == "    ]")
pat = re.compile(r'^\s+"((?:[^"\\]|\\.)*)": "((?:[^"\\]|\\.)*)",$')

out = ["// Generated by gen_ru.py from Localization.swift's Russian table. Do not edit.", "", "pub(super) static RUSSIAN: &[(&str, &str)] = &["]
count = 0
for line in src[start + 1:end]:
    if not line.strip() or line.strip().startswith("//"):
        continue
    m = pat.match(line)
    if not m:
        raise SystemExit(f"unrecognised line in the table: {line!r}")
    # Swift and Rust agree on \" and \n; nothing else is escaped in the table.
    out.append(f'    ("{m.group(1)}", "{m.group(2)}"),')
    count += 1
out.append("];")
out.append("")
(root / "linux/crates/core/src/loc/ru.rs").write_text("\n".join(out))
print(f"{count} entries")
