extension Localization {
    /// The Translator's sentences, kept apart from the main table so the
    /// Module's words can be found, and changed, together (ticket 28).
    public static let translatorRussian: [String: String] = [
        "Translator": "Переводчик",
        "Russian and English, translated on this Mac.": "Русский и английский, перевод на этом Mac.",
        "Translation on this Mac needs macOS 26 or later.": "Для перевода на этом Mac нужна macOS 26 или новее.",
        "CapaTheNotch uses Apple's on-device translation, which apps can use without a window only from macOS 26.": "CapaTheNotch переводит встроенным переводчиком Apple, а приложения могут пользоваться им без окна только начиная с macOS 26.",
        "Download Russian and English for translation in Translator settings.": "Загрузите русский и английский для перевода в настройках переводчика.",
        "The translation failed. Try again.": "Перевести не удалось. Попробуйте ещё раз.",
        "Translate selection": "Перевести выделенное",
        "Languages": "Языки",
        "Russian and English ready": "Русский и английский готовы",
        "Checking…": "Проверка…",
        "Asking macOS…": "Запрос к macOS…",
        "Download…": "Загрузить…",
        "Russian and English are downloaded by macOS, which asks you first. Apple does not tell apps the size in advance. The languages are shared with other apps and can be removed in System Settings › General › Language & Region › Translation Languages.": "Русский и английский загружает macOS — сначала она спросит вас. Размер загрузки Apple приложениям заранее не сообщает. Языки общие для всех приложений; удалить их можно в Системных настройках › Основные › Язык и регион › Языки перевода.",
        "The translation could not be put in place. It is on the clipboard.": "Перевод не удалось вставить на место. Он в буфере обмена.",
        "Select text to translate first.": "Сначала выделите текст для перевода.",
        "Allow Accessibility in Translator settings to translate a selection.": "Чтобы переводить выделенное, разрешите Универсальный доступ в настройках переводчика.",
        "Password fields are not translated.": "Поля паролей не переводятся.",
        "There is nothing to translate in the selection.": "В выделенном нечего переводить.",
        "Translate the other way": "Перевести в другую сторону",
        "Direction": "Направление",
        "Russian to English": "С русского на английский",
        "English to Russian": "С английского на русский",
        "Clear": "Очистить",
        "Copy": "Копировать",
        "Copied": "Скопировано",
        "Translating…": "Перевод…",
        "Turned round": "Направление изменено",
        "%@ translates a selection": "%@ переводит выделенное",
        "Type or paste text": "Напишите или вставьте текст",
        "Text to translate": "Текст для перевода",
        "Translation": "Перевод",
        "Translator Settings…": "Настройки переводчика…",
        "Russian and English are not downloaded for translation yet.": "Русский и английский для перевода ещё не загружены.",
        "Checking translation languages…": "Проверка языков перевода…",
        // The selection brought to the notch (2026-10-07).
        "Select text in any app and press the shortcut — the surface opens with the translation. You can copy it, and if the selection is in a text field, paste it in place of the selection. macOS translates on this Mac; the text goes nowhere.": "Выделите текст в любом приложении и нажмите сочетание — шторка откроется с переводом. Его можно скопировать, а если выделено в поле ввода — вставить вместо выделенного. Переводит macOS на этом Mac; текст никуда не уходит.",
        "Accessibility lets the shortcut read the selection and, when you ask, put the translation in its place; your clipboard is put back after. The text is never saved or logged.": "Универсальный доступ нужен, чтобы сочетание читало выделенное и по вашей просьбе ставило перевод на его место; буфер обмена потом возвращается как был. Текст не сохраняется и не пишется в журнал.",
        "from %@": "из %@",
        "from %@ · not a text field": "из %@ · не поле ввода",
        "not a text field": "не поле ввода",
        "Paste in place of the selection": "Вставить вместо выделенного",
        "Selected text": "Выделенный текст",
        "Press Return": "Нажмите Return",
    ]
}
