import CapacityNotchCore
import Foundation

private let start = Date(timeIntervalSince1970: 1_000_000)

func clippingsAreNewestFirstAndARepeatRises() throws {
    var clippings = Clippings()
    clippings.keep("один", at: start)
    clippings.keep("два", at: start.addingTimeInterval(1))
    clippings.keep("один", at: start.addingTimeInterval(2))
    try expect(clippings.items.map(\.text) == ["один", "два"], "A repeat rises rather than appearing twice, got \(clippings.items.map(\.text))")
    try expect(clippings.items.first?.copiedAt == start.addingTimeInterval(2), "with the time it was copied again")
}

func clippingsKeepTwentyOrFiftyOrAHundred() throws {
    try expect(ClippingLimit.allCases.map(\.rawValue) == [20, 50, 100], "20, 50 or 100")
    try expect(ClippingLimit.default == .twenty, "20 unless chosen")
    var clippings = Clippings()
    for index in 1...60 { clippings.keep("\(index)", at: start.addingTimeInterval(Double(index)), limit: .fifty) }
    try expect(clippings.items.count == 50, "Fifty when chosen, got \(clippings.items.count)")
    try expect(clippings.items.first?.text == "60" && clippings.items.last?.text == "11", "The oldest give way")
    clippings.keep("61", at: start.addingTimeInterval(61), limit: .twenty)
    try expect(clippings.items.count == 20, "Down to twenty when that is chosen again, got \(clippings.items.count)")
}

func aClippingGoesAfterADayUnlessThatIsSwitchedOff() throws {
    var clippings = Clippings()
    clippings.keep("старый", at: start)
    clippings.keep("новый", at: start.addingTimeInterval(3600))
    var kept = clippings
    kept.forgetOld(at: start.addingTimeInterval(24 * 3600 + 1), expiring: false)
    try expect(kept.items.count == 2, "Expiry switched off keeps both")
    clippings.forgetOld(at: start.addingTimeInterval(24 * 3600 - 1), expiring: true)
    try expect(clippings.items.count == 2, "Not before the day is out")
    clippings.forgetOld(at: start.addingTimeInterval(24 * 3600), expiring: true)
    try expect(clippings.items.map(\.text) == ["новый"], "At 24 hours it goes, got \(clippings.items.map(\.text))")
}

func aTextTooLongOrEmptyIsNotKeptAtAll() throws {
    var clippings = Clippings()
    try expect(!clippings.keep(String(repeating: "a", count: 100_001), at: start), "Over 100,000 characters, not kept")
    try expect(clippings.keep(String(repeating: "a", count: 100_000), at: start), "100,000 exactly is kept")
    try expect(!clippings.keep("  \n ", at: start), "Nothing but spaces is nothing")
    try expect(clippings.items.count == 1, "Only the one that fits")
}

func aClippingIsRemovedAloneAndClearingEmptiesThem() throws {
    var clippings = Clippings()
    clippings.keep("a", at: start)
    clippings.keep("b", at: start)
    let b = try unwrapClipping(clippings.items.first { $0.text == "b" })
    clippings.remove(b.id)
    try expect(clippings.items.map(\.text) == ["a"], "Only that one goes")
    clippings.clear()
    try expect(clippings.items.isEmpty, "Clearing empties them")
}

func onlyPlainTextCopiedElsewhereAndUnmarkedIsKept() throws {
    func keeps(_ types: [String], front: String? = "com.apple.Safari", excluded: Set<String> = []) -> Bool {
        ClipboardText.isKept(types: [types], frontmost: front, excluded: excluded, ownApplication: "app.capacitynotch.CapacityNotch")
    }
    try expect(keeps(["public.utf8-plain-text"]), "Plain text")
    try expect(keeps(["public.html", "public.utf8-plain-text", "public.rtf"]), "Text copied from a page")
    try expect(!keeps(["public.png"]), "An image is not text")
    try expect(!keeps(["public.file-url", "public.utf8-plain-text"]), "A copied file's name is not a Clipping")
    try expect(!keeps(["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]), "Concealed")
    try expect(!keeps(["public.utf8-plain-text", "org.nspasteboard.TransientType"]), "Transient")
    try expect(!keeps(["public.utf8-plain-text", "org.nspasteboard.AutoGeneratedType"]), "Auto-generated")
    try expect(!keeps(["public.utf8-plain-text", "com.agilebits.onepassword"]), "An older marker")
    try expect(!keeps(["public.utf8-plain-text"], front: "com.apple.Passwords"), "Copied while Passwords is in front")
    try expect(!keeps(["public.utf8-plain-text"], front: "com.apple.keychainaccess"), "or Keychain Access")
    try expect(!keeps(["public.utf8-plain-text"], front: "ru.bank.app", excluded: ["ru.bank.app"]), "or an application chosen in Settings")
    try expect(!keeps(["public.utf8-plain-text", ClipboardText.ownMarker]), "Never what CapaTheNotch put there itself")
    try expect(
        !keeps(["public.utf8-plain-text"], front: "app.capacitynotch.CapacityNotch"),
        "Nor what is copied with ⌘C in its own windows — Dictation's history, the report"
    )
    try expect(!ClipboardText.isKept(types: [], frontmost: nil, excluded: [], ownApplication: nil), "Nothing is nothing")
}

private func unwrapClipping<T>(_ value: T?) throws -> T {
    guard let value else { throw TestFailure(description: "Expected a value") }
    return value
}

func theSurfaceStaysOutOfCaptureWhileItHoldsAClipping() throws {
    try expect(
        TeleprompterSurface.excludedFromCapture(sharingAllowed: true, teleprompterShowing: false, holdsClippings: true),
        "Allowed in sharing, and still not shared while a Clipping is held"
    )
    try expect(
        !TeleprompterSurface.excludedFromCapture(sharingAllowed: true, teleprompterShowing: false, holdsClippings: false),
        "None held, the switch decides again"
    )
}

func theShelfTellsDiagnosticsHowManyClippingsNeverWhich() throws {
    var clippings = Clippings()
    clippings.keep("секрет", at: start)
    let said = ShelfModule.observation(enabled: true, shelf: Shelf(), clippings: clippings)
    try expect(said == "shelf-on-0-files-0-screenshots-1-clippings", "Counts only, got \(said)")
    try expect(!said.contains("секрет"), "Never what was copied")
}

func textIntakeIsOffUntilAskedForAndKeepsADay() throws {
    let suite = "clippings-\(UUID())"
    let defaults = try unwrapClipping(UserDefaults(suiteName: suite))
    defer { defaults.removePersistentDomain(forName: suite) }
    let preferences = Preferences(defaults: defaults)
    try expect(!preferences.shelfKeepsText, "Text intake off until turned on")
    try expect(preferences.clippingLimit == .twenty, "Twenty Clippings")
    try expect(preferences.clippingsExpire, "Each gone after a day")
    try expect(preferences.clipboardExcludedApplications.isEmpty, "No application chosen")
    preferences.clippingLimit = .hundred
    preferences.clippingsExpire = false
    preferences.clipboardExcludedApplications = ["ru.bank.app"]
    let again = Preferences(defaults: defaults)
    try expect(again.clippingLimit == .hundred && !again.clippingsExpire, "Choices are kept")
    try expect(again.clipboardExcludedApplications == ["ru.bank.app"], "and the applications chosen")
}

func theClipboardTabCountsItsClippingsAsEachLanguageDoes() throws {
    try expect(Localization.clippingCount(1, in: .english) == "1 clipping", "One")
    try expect(Localization.clippingCount(4, in: .english) == "4 clippings", "Many")
    try expect(Localization.clippingCount(1, in: .russian) == "1 текст", "Один текст")
    try expect(Localization.clippingCount(3, in: .russian) == "3 текста", "Три текста")
    try expect(Localization.clippingCount(12, in: .russian) == "12 текстов", "Двенадцать текстов")
}

func fewerChosenTheOldestGoAtOnceAndTheRestStayAsTheyWere() throws {
    var clippings = Clippings()
    for index in 1...30 { clippings.keep("\(index)", at: start.addingTimeInterval(Double(index)), limit: .fifty) }
    let newest = try unwrapClipping(clippings.items.first)
    clippings.trim(to: .twenty)
    try expect(clippings.items.count == 20, "Twenty, got \(clippings.items.count)")
    try expect(clippings.items.first == newest, "The newest unchanged, the same Clipping as before")
    try expect(clippings.items.last?.text == "11", "The oldest gone, got \(clippings.items.last?.text ?? "nothing")")
}
