import Darwin

struct TestFailure: Error, CustomStringConvertible {
    let description: String
}

func expect(_ condition: @autoclosure () -> Bool, _ message: String) throws {
    guard condition() else {
        throw TestFailure(description: message)
    }
}

@main
enum CapacityNotchTestRunner {
    static func main() async {
        let tests: [(String, () async throws -> Void)] = [
            (
                "CapacitySnapshotTests.quotaWindowReportsThirtyPercentLeftAfterSeventyPercentIsUsed",
                quotaWindowReportsThirtyPercentLeftAfterSeventyPercentIsUsed
            ),
            (
                "CapacitySnapshotTests.disconnectedCapacityCarriesGuidanceAndNoWindows",
                disconnectedCapacityCarriesGuidanceAndNoWindows
            ),
            (
                "MockCapacityCatalogTests.mockCatalogProvidesBothInitialProviders",
                mockCatalogProvidesBothInitialProviders
            ),
            (
                "MockCapacityCatalogTests.mockCatalogMarksCapacityAsMock",
                mockCatalogMarksCapacityAsMock
            ),
            (
                "CapacityNotchStoreTests.storeMovesBetweenCompactAndExpandedPresentation",
                storeMovesBetweenCompactAndExpandedPresentation
            ),
            (
                "CapacityNotchStoreTests.storeReplacesTheCapacityOfTheProviderItDescribes",
                storeReplacesTheCapacityOfTheProviderItDescribes
            ),
            (
                "CodexAppServerProtocolTests.inboundParserSeparatesResponsesFailuresAndNotifications",
                inboundParserSeparatesResponsesFailuresAndNotifications
            ),
            (
                "CodexAppServerProtocolTests.outboundRequestsAreOneJSONLine",
                outboundRequestsAreOneJSONLine
            ),
            (
                "CodexAppServerProtocolTests.codexWindowsBecomeQuotaWindowsWithRemainingCapacity",
                codexWindowsBecomeQuotaWindowsWithRemainingCapacity
            ),
            (
                "CodexAppServerProtocolTests.windowLabelsCoverTheDurationsCodexReports",
                windowLabelsCoverTheDurationsCodexReports
            ),
            (
                "CodexAppServerProtocolTests.rollingUpdatesKeepWindowsTheyOmit",
                rollingUpdatesKeepWindowsTheyOmit
            ),
            (
                "CodexAppServerProtocolTests.codexBinaryIsFoundOnlyWhereItIsExecutable",
                codexBinaryIsFoundOnlyWhereItIsExecutable
            ),
            (
                "DiagnosticsTests.aProvidersOwnWordsNeverReachTheReport",
                aProvidersOwnWordsNeverReachTheReport
            ),
            (
                "DiagnosticsTests.scrubbingCatchesWhatGetsInFromOutside",
                scrubbingCatchesWhatGetsInFromOutside
            ),
            (
                "DiagnosticsTests.aBugReportCanTellWhyTheBridgeFileCannotBeRead",
                aBugReportCanTellWhyTheBridgeFileCannotBeRead
            ),
            (
                "DiagnosticsTests.theReportStaysUsefulForEveryFailureWorthReporting",
                theReportStaysUsefulForEveryFailureWorthReporting
            ),
            (
                "DiagnosticsTests.theReportSaysWhatAMaintainerNeedsToKnow",
                theReportSaysWhatAMaintainerNeedsToKnow
            ),
            (
                "CapacityAlertTests.aWindowFallingBelowTenPercentIsWorthSaying",
                aWindowFallingBelowTenPercentIsWorthSaying
            ),
            (
                "CapacityAlertTests.aWindowSaysItOnceAndThenKeepsQuiet",
                aWindowSaysItOnceAndThenKeepsQuiet
            ),
            (
                "CapacityAlertTests.aWindowThatRecoversIsNewsWhenItFallsAgain",
                aWindowThatRecoversIsNewsWhenItFallsAgain
            ),
            (
                "CapacityAlertTests.aWindowThatTurnsOverIsANewWindow",
                aWindowThatTurnsOverIsANewWindow
            ),
            (
                "CapacityAlertTests.onlyAFreshReadingSpeaks",
                onlyAFreshReadingSpeaks
            ),
            (
                "CapacityAlertTests.aSilencedProviderIsSilentAndStaysCaughtUp",
                aSilencedProviderIsSilentAndStaysCaughtUp
            ),
            (
                "CapacityAlertTests.disconnectingAProviderForgetsWhatWasSaid",
                disconnectingAProviderForgetsWhatWasSaid
            ),
            (
                "CapacitySpeechTests.aWindowSaysEverythingTheCardShows",
                aWindowSaysEverythingTheCardShows
            ),
            (
                "CapacitySpeechTests.aWindowWithNoResetSaysSoRatherThanInventingOne",
                aWindowWithNoResetSaysSoRatherThanInventingOne
            ),
            (
                "CapacitySpeechTests.aProviderSaysWhoItIsAndHowItsReadingStands",
                aProviderSaysWhoItIsAndHowItsReadingStands
            ),
            (
                "CapacitySpeechTests.anUnreadableProviderSaysTheOneThingThatWouldFixIt",
                anUnreadableProviderSaysTheOneThingThatWouldFixIt
            ),
            (
                "CapacitySpeechTests.theClosedStripSaysTheWindowItIsShowing",
                theClosedStripSaysTheWindowItIsShowing
            ),
            (
                "CapacitySpeechTests.theStatesAreTellableApartWithoutColour",
                theStatesAreTellableApartWithoutColour
            ),
            (
                "PreferencesTests.nothingIsEnabledOnAnybodysBehalf",
                nothingIsEnabledOnAnybodysBehalf
            ),
            (
                "PreferencesTests.codexStartsConnectedAndClaudeDoesNot",
                codexStartsConnectedAndClaudeDoesNot
            ),
            (
                "PreferencesTests.onboardingIsOfferedOnlyToSomeoneWhoHasConnectedNothing",
                onboardingIsOfferedOnlyToSomeoneWhoHasConnectedNothing
            ),
            (
                "PreferencesTests.aDeliberateDisconnectOutlivesTheLaunchItWasMadeIn",
                aDeliberateDisconnectOutlivesTheLaunchItWasMadeIn
            ),
            (
                "PreferencesTests.aChoiceMadeAnywhereIsTheSameChoice",
                aChoiceMadeAnywhereIsTheSameChoice
            ),
            (
                "PreferencesTests.theBackgroundPaceFallsBackToTheScheduleItCameFrom",
                theBackgroundPaceFallsBackToTheScheduleItCameFrom
            ),
            (
                "CapacityArchiveTests.whatWasSeenLastComesBackAsStale",
                whatWasSeenLastComesBackAsStale
            ),
            (
                "CapacityArchiveTests.aProviderWithNothingToShowIsNotRemembered",
                aProviderWithNothingToShowIsNotRemembered
            ),
            (
                "CapacityArchiveTests.anUnreadableArchiveCostsNothing",
                anUnreadableArchiveCostsNothing
            ),
            (
                "CapacityArchiveTests.aRestartOpensOnWhatWasThereAndAsksForTheRest",
                aRestartOpensOnWhatWasThereAndAsksForTheRest
            ),
            (
                "CapacityArchiveTests.theWaitStretchesWhileAProviderIsFailing",
                theWaitStretchesWhileAProviderIsFailing
            ),
            (
                "CapacityArchiveTests.aFailureWorthRetryingIsToldFromOneThatIsNot",
                aFailureWorthRetryingIsToldFromOneThatIsNot
            ),
            (
                "SurfacePlacementTests.theBuiltInDisplayIsTheDefaultAndOneIsAlwaysChosen",
                theBuiltInDisplayIsTheDefaultAndOneIsAlwaysChosen
            ),
            (
                "SurfacePlacementTests.aDisplayThatIsUnpluggedDoesNotStrandTheSurface",
                aDisplayThatIsUnpluggedDoesNotStrandTheSurface
            ),
            (
                "SurfacePlacementTests.hidingPutsTheSurfaceAwayAndBringsItBack",
                hidingPutsTheSurfaceAwayAndBringsItBack
            ),
            (
                "SurfacePlacementTests.aPinnedSurfaceStaysUntilItIsDismissed",
                aPinnedSurfaceStaysUntilItIsDismissed
            ),
            (
                "CapacityPaceTests.theStateIsReadOffWhatIsLeft",
                theStateIsReadOffWhatIsLeft
            ),
            (
                "CapacityPaceTests.theClockDoesNotChangeTheColour",
                theClockDoesNotChangeTheColour
            ),
            (
                "CapacityPaceTests.theHeadlineIsTheScarcestWindow",
                theHeadlineIsTheScarcestWindow
            ),
            (
                "CapacityPaceTests.theCountdownSaysHowLongInTheFewestWords",
                theCountdownSaysHowLongInTheFewestWords
            ),
            (
                "ClaudeUsageCommandTests.theUsageReportBecomesQuotaWindows",
                theUsageReportBecomesQuotaWindows
            ),
            (
                "ClaudeUsageCommandTests.proseThatNoLongerParsesIsNotAReading",
                proseThatNoLongerParsesIsNotAReading
            ),
            (
                "ClaudeUsageCommandTests.aWindowInWordingNotKnownRefusesTheWholeReport",
                aWindowInWordingNotKnownRefusesTheWholeReport
            ),
            (
                "ClaudeUsageCommandTests.windowsLeftOutOnPurposeOrNotPrintedAreNotAChangedReport",
                windowsLeftOutOnPurposeOrNotPrintedAreNotAChangedReport
            ),
            (
                "ClaudeUsageCommandTests.aWindowWithoutAYearReadsAsTheOneAhead",
                aWindowWithoutAYearReadsAsTheOneAhead
            ),
            (
                "ClaudeUsageCommandTests.theNewerOfTwoSourcesWins",
                theNewerOfTwoSourcesWins
            ),
            (
                "ClaudeUsageCommandTests.aBridgeThatWasNeverSetUpDoesNotHideWhyUsageFailed",
                aBridgeThatWasNeverSetUpDoesNotHideWhyUsageFailed
            ),
            (
                "ClaudeUsageCommandTests.aBrokenBridgeFileDoesNotHideWhyUsageFailed",
                aBrokenBridgeFileDoesNotHideWhyUsageFailed
            ),
            (
                "ClaudeUsageCommandTests.anOldReadingDoesNotHideWhyTheOtherSourceFailed",
                anOldReadingDoesNotHideWhyTheOtherSourceFailed
            ),
            (
                "ClaudeUsageCommandTests.aClaudeCodeThatHangsIsGivenUpOnAtTheTimeout",
                aClaudeCodeThatHangsIsGivenUpOnAtTheTimeout
            ),
            (
                "ClaudeUsageCommandTests.anAnswerBeforeTheTimeoutIsStillRead",
                anAnswerBeforeTheTimeoutIsStillRead
            ),
            (
                "ClaudeUsageCommandTests.askingClaudeCodeIsThrottled",
                askingClaudeCodeIsThrottled
            ),
            (
                "UnreadCapacityTests.anUnreadSurfaceShowsNoNumbersAtAll",
                anUnreadSurfaceShowsNoNumbersAtAll
            ),
            (
                "NotchGeometryTests.theCompactSurfaceTakesItsHeightFromTheMenuBar",
                theCompactSurfaceTakesItsHeightFromTheMenuBar
            ),
            (
                "CodexAppServerProtocolTests.theSurfaceHeaderDescribesWhatItIsActuallyShowing",
                theSurfaceHeaderDescribesWhatItIsActuallyShowing
            ),
            (
                "CodexCapacityServiceTests.connectingCodexPublishesFreshCapacityFromTheAppServer",
                connectingCodexPublishesFreshCapacityFromTheAppServer
            ),
            (
                "CodexCapacityServiceTests.connectingTwiceDoesNotStartASecondAppServer",
                connectingTwiceDoesNotStartASecondAppServer
            ),
            (
                "CodexCapacityServiceTests.rollingUpdatesReachTheSurfaceWithoutReconnecting",
                rollingUpdatesReachTheSurfaceWithoutReconnecting
            ),
            (
                "CodexCapacityServiceTests.disconnectingEndsOnlyTheAppServerCapacityNotchStarted",
                disconnectingEndsOnlyTheAppServerCapacityNotchStarted
            ),
            (
                "CodexCapacityServiceTests.missingCodexProducesAnActionableDisconnectedState",
                missingCodexProducesAnActionableDisconnectedState
            ),
            (
                "CodexCapacityServiceTests.anIncompatibleCodexProducesAnActionableDisconnectedState",
                anIncompatibleCodexProducesAnActionableDisconnectedState
            ),
            (
                "CodexCapacityServiceTests.anUnauthenticatedCodexProducesAnActionableDisconnectedState",
                anUnauthenticatedCodexProducesAnActionableDisconnectedState
            ),
            (
                "CodexCapacityServiceTests.anAppServerThatStopsLeavesADisconnectedProviderNotZeroCapacity",
                anAppServerThatStopsLeavesADisconnectedProviderNotZeroCapacity
            ),
            (
                "CodexCapacityServiceTests.capacityNotchOnlyEverSendsCodexReadMethods",
                capacityNotchOnlyEverSendsCodexReadMethods
            ),
            (
                "CodexCapacityServiceTests.aClientRefusesToSendAMethodOutsideTheReadSet",
                aClientRefusesToSendAMethodOutsideTheReadSet
            ),
            (
                "CapacityNotchStoreTests.askingForTheStateAlreadyHeldAnnouncesNothing",
                askingForTheStateAlreadyHeldAnnouncesNothing
            ),
            (
                "CodexCapacityServiceTests.aFailedRefreshKeepsTheLastCapacityAsStale",
                aFailedRefreshKeepsTheLastCapacityAsStale
            ),
            (
                "CodexCapacityServiceTests.aCodexAnswerInAShapeNotKnownKeepsTheLastCapacityAndSaysWhy",
                aCodexAnswerInAShapeNotKnownKeepsTheLastCapacityAndSaysWhy
            ),
            (
                "CodexCapacityServiceTests.aFirstCodexAnswerInAShapeNotKnownSaysWhy",
                aFirstCodexAnswerInAShapeNotKnownSaysWhy
            ),
            (
                "CodexCapacityServiceTests.staleCodexCapacityKeepsTheMomentItWasRead",
                staleCodexCapacityKeepsTheMomentItWasRead
            ),
            (
                "CodexCapacityServiceTests.aCodexThatAnswersWithAnErrorSaysSoOverItsStaleCapacity",
                aCodexThatAnswersWithAnErrorSaysSoOverItsStaleCapacity
            ),
            (
                "CodexCapacityServiceTests.anAccountAnswerOutsideTheSchemaIsNotReadAsSignedOut",
                anAccountAnswerOutsideTheSchemaIsNotReadAsSignedOut
            ),
            (
                "CodexCapacityServiceTests.anAccountAnswerWithNoAccountIsSignedOutAsTheSchemaAllows",
                anAccountAnswerWithNoAccountIsSignedOutAsTheSchemaAllows
            ),
            (
                "CodexCapacityServiceTests.aFirstReadThatFailsHasNoCapacityToHold",
                aFirstReadThatFailsHasNoCapacityToHold
            ),
            (
                "LiveArchiveTests.liveArchiveReadsBackWhatTheAppWrote",
                liveArchiveReadsBackWhatTheAppWrote
            ),
            (
                "LiveClaudeUsageTests.liveClaudeUsageReportsCapacity",
                liveClaudeUsageReportsCapacity
            ),
            (
                "LiveCodexTests.liveCodexPublishesFreshCapacity",
                liveCodexPublishesFreshCapacity
            ),
            (
                "ClaudeCapacityServiceTests.connectingClaudeReadsFreshCapacityPublishedByClaudeCode",
                connectingClaudeReadsFreshCapacityPublishedByClaudeCode
            ),
            (
                "ClaudeCapacityServiceTests.anOldClaudeStatusLineReadingIsStaleCapacity",
                anOldClaudeStatusLineReadingIsStaleCapacity
            ),
            (
                "ClaudeCapacityServiceTests.aFailedClaudeBridgeRefreshKeepsTheLastCapacityAsStale",
                aFailedClaudeBridgeRefreshKeepsTheLastCapacityAsStale
            ),
            (
                "ClaudeCapacityServiceTests.publishingClaudeStatusLineWritesOnlyCapacitySnapshot",
                publishingClaudeStatusLineWritesOnlyCapacitySnapshot
            ),
            (
                "ClaudeCapacityServiceTests.fileClaudeCapacitySourceReadsPublishedQuotaWindows",
                fileClaudeCapacitySourceReadsPublishedQuotaWindows
            ),
            (
                "ClaudeCapacityServiceTests.eachWayAskingClaudeCodeFailsSaysItsOwnFix",
                eachWayAskingClaudeCodeFailsSaysItsOwnFix
            ),
            (
                "ClaudeCapacityServiceTests.aBridgeFromYesterdayDoesNotReplaceTheLastCapacityRead",
                aBridgeFromYesterdayDoesNotReplaceTheLastCapacityRead
            ),
            (
                "ClaudeCapacityServiceTests.missingClaudeStatusLineSnapshotIsActionableAndDisconnected",
                missingClaudeStatusLineSnapshotIsActionableAndDisconnected
            ),
            (
                "ClaudeCapacityServiceTests.disconnectingClaudeClearsFreshCapacityFromTheSurface",
                disconnectingClaudeClearsFreshCapacityFromTheSurface
            ),
        ]
        let selection = CommandLine.arguments.dropFirst().first
        let selected = tests.filter { selection == nil || $0.0 == selection }

        guard !selected.isEmpty else {
            print("No test matched \(selection ?? "")")
            exit(2)
        }

        var failures = 0
        for (name, test) in selected {
            do {
                try await test()
                print("PASS \(name)")
            } catch {
                failures += 1
                print("FAIL \(name): \(error)")
            }
        }

        exit(failures == 0 ? 0 : 1)
    }
}
