import Darwin

struct TestFailure: Error, CustomStringConvertible {
    let description: String
}

func expect(_ condition: @autoclosure () -> Bool, _ message: String) throws {
    guard condition() else {
        throw TestFailure(description: message)
    }
}

@main
enum CapacityNotchTestRunner {
    static func main() async {
        let tests: [(String, () async throws -> Void)] = [
            ("Dictation.replacements", dictationReplacesPhrasesWithoutSubstringsOrCascades),
            ("Dictation.history", dictationHistoryIsOptInBoundedAndPersistent),
            ("Dictation.session", dictationStopsOnceAndRejectsCancelledResults),
            ("Localization.translationsKeepTheirArguments", everyTranslationKeepsItsSentencesNumbersAndNames),
            ("Localization.systemFollowsTheMac", systemLanguageFollowsTheMacsFirstLanguage),
            ("Localization.missingFallsBackToEnglish", aSentenceWithoutATranslationIsShownAsWritten),
            ("Localization.choiceIsRemembered", theLanguageChoiceIsRemembered),
            ("Localization.russianAlert", aRussianAlertSaysItAllInRussian),
            ("CompactStrip.oneProvider", theStripShowsTheOnlyProvidersShortWindowLeftAndLongRight),
            ("CompactStrip.bothProviders", theStripShowsEachProvidersFiveHoursWhenBothAreOn),
            ("CompactStrip.nothingConnected", nothingConnectedLeavesTheStripEmptyAndTheSurfaceOpen),
            ("Codex.chatGPTBundled", theCodexInChatGPTIsFoundWhereNewerReleasesKeepIt),
            ("Codex.environment", codexRunsWithThePathATerminalWouldGiveIt),
            ("Shelf.newestFirstAndTwenty", theShelfKeepsTheNewestFirstAndAtMostTwenty),
            ("Shelf.droppedAgainRises", aFileDroppedAgainRisesInsteadOfAppearingTwice),
            ("Shelf.removeAndClear", aFileIsRemovedAloneAndClearingEmptiesTheShelf),
            ("Shelf.fileKinds", aFileIsDrawnByWhatKindItIs),
            ("Shelf.diagnostics", theShelfTellsDiagnosticsHowManyNeverWhich),
            ("Shelf.pageOrder", pagesRunCapacityMusicTeleprompterShelf),
            ("Shelf.dropTabOutline", theDropTabIsPartOfTheSurfacesOwnOutline),
            ("Shelf.fileCount", theShelfCountsItsFilesAsEachLanguageDoes),
            ("Shelf.imageInMemory", anImageWithoutAFileIsHeldInMemory),
            ("Shelf.screenshotClipboard", aScreenshotOnTheClipboardIsOnePNGAndNothingElse),
            ("Shelf.screenshotName", aScreenshotIsNamedAsMacOSNamesOne),
            ("Shelf.clipboard", whatIsCopiedLandsOnTheShelfExceptFromFinder),
            ("CompactStrip.choice", theStripShowsTheWindowChosenInSettings),
            ("CompactStrip.choiceByLength", theChosenWindowIsTheOneOfThatLengthNotTheShortestOrLongest),
            ("Diagnostics.dictationStatesReachTheReport", dictationStatesReachTheReportWhole),
            ("Diagnostics.logLinesCarryCodes", aLogLineCarriesCodesAndNeverDescriptions),
            (
                "TeleprompterTests.aScriptTakesAMinuteAtLeastAndRoundsToTheNearest",
                aScriptTakesAMinuteAtLeastAndRoundsToTheNearest
            ),
            (
                "TeleprompterTests.aScriptKeepsItsLineBreaksAndBlankLinesAndWrapsTheRest",
                aScriptKeepsItsLineBreaksAndBlankLinesAndWrapsTheRest
            ),
            (
                "TeleprompterTests.draggingTheProgressOfAStoppedScriptChoosesWhereItStarts",
                draggingTheProgressOfAStoppedScriptChoosesWhereItStarts
            ),
            (
                "TeleprompterTests.aScriptCountsItsWordsAcrossLinesAndSpaces",
                aScriptCountsItsWordsAcrossLinesAndSpaces
            ),
            (
                "TeleprompterTests.pastingReplacesTheScriptAndOnlyTheOneBeforeComesBack",
                pastingReplacesTheScriptAndOnlyTheOneBeforeComesBack
            ),
            (
                "TeleprompterTests.theTeleprompterIsOffWithQuietDefaults",
                theTeleprompterIsOffWithQuietDefaults
            ),
            (
                "TeleprompterTests.aRecordedKeyIsNamedAsTheKeycapShowsIt",
                aRecordedKeyIsNamedAsTheKeycapShowsIt
            ),
            (
                "TeleprompterTests.startingHoldsTheFirstLineThenMovesAtTheChosenSpeed",
                startingHoldsTheFirstLineThenMovesAtTheChosenSpeed
            ),
            (
                "TeleprompterTests.anEmptyScriptDoesNotStart",
                anEmptyScriptDoesNotStart
            ),
            (
                "TeleprompterTests.pauseHoldsThePlaceAndResumeGoesOnFromIt",
                pauseHoldsThePlaceAndResumeGoesOnFromIt
            ),
            (
                "TeleprompterTests.stopClearsTheRowAndStartsOver",
                stopClearsTheRowAndStartsOver
            ),
            (
                "TeleprompterTests.fasterAndSlowerChangeTheSpeedInQuarters",
                fasterAndSlowerChangeTheSpeedInQuarters
            ),
            (
                "TeleprompterTests.fingersMoveTheScriptAndPauseIt",
                fingersMoveTheScriptAndPauseIt
            ),
            (
                "TeleprompterTests.draggingTheProgressGoesAnywhereInTheScript",
                draggingTheProgressGoesAnywhereInTheScript
            ),
            (
                "TeleprompterTests.atTheEndItStopsOnTheLastLineAndTheRowLeavesAfterThreeSeconds",
                atTheEndItStopsOnTheLastLineAndTheRowLeavesAfterThreeSeconds
            ),
            (
                "TeleprompterTests.timeSpentAndLeftFollowThePlace",
                timeSpentAndLeftFollowThePlace
            ),
            (
                "TeleprompterTests.aNewLayoutKeepsThePlaceInTheScript",
                aNewLayoutKeepsThePlaceInTheScript
            ),
            (
                "TeleprompterTests.theTeleprompterRowTakesThePlaceOfTheMusicRow",
                theTeleprompterRowTakesThePlaceOfTheMusicRow
            ),
            (
                "TeleprompterTests.whileItShowsTheSurfaceStaysOutOfCaptureAndHoverDoesNotOpenIt",
                whileItShowsTheSurfaceStaysOutOfCaptureAndHoverDoesNotOpenIt
            ),
            (
                "TeleprompterTests.pagesRunCapacityMusicTeleprompter",
                pagesRunCapacityMusicTeleprompter
            ),
            (
                "TeleprompterTests.diagnosticsSayHowLongTheScriptIsAndNeverWhatItSays",
                diagnosticsSayHowLongTheScriptIsAndNeverWhatItSays
            ),
            (
                "CapacitySnapshotTests.quotaWindowReportsThirtyPercentLeftAfterSeventyPercentIsUsed",
                quotaWindowReportsThirtyPercentLeftAfterSeventyPercentIsUsed
            ),
            (
                "CapacitySnapshotTests.disconnectedCapacityCarriesGuidanceAndNoWindows",
                disconnectedCapacityCarriesGuidanceAndNoWindows
            ),
            (
                "MockCapacityCatalogTests.mockCatalogProvidesBothInitialProviders",
                mockCatalogProvidesBothInitialProviders
            ),
            (
                "MockCapacityCatalogTests.mockCatalogMarksCapacityAsMock",
                mockCatalogMarksCapacityAsMock
            ),
            (
                "CapacityNotchStoreTests.storeMovesBetweenCompactAndExpandedPresentation",
                storeMovesBetweenCompactAndExpandedPresentation
            ),
            (
                "CapacityNotchStoreTests.storeReplacesTheCapacityOfTheProviderItDescribes",
                storeReplacesTheCapacityOfTheProviderItDescribes
            ),
            (
                "CodexAppServerProtocolTests.inboundParserSeparatesResponsesFailuresAndNotifications",
                inboundParserSeparatesResponsesFailuresAndNotifications
            ),
            (
                "CodexAppServerProtocolTests.outboundRequestsAreOneJSONLine",
                outboundRequestsAreOneJSONLine
            ),
            (
                "CodexAppServerProtocolTests.codexWindowsBecomeQuotaWindowsWithRemainingCapacity",
                codexWindowsBecomeQuotaWindowsWithRemainingCapacity
            ),
            (
                "CodexAppServerProtocolTests.windowLabelsCoverTheDurationsCodexReports",
                windowLabelsCoverTheDurationsCodexReports
            ),
            (
                "CodexAppServerProtocolTests.rollingUpdatesKeepWindowsTheyOmit",
                rollingUpdatesKeepWindowsTheyOmit
            ),
            (
                "CodexAppServerProtocolTests.codexBinaryIsFoundOnlyWhereItIsExecutable",
                codexBinaryIsFoundOnlyWhereItIsExecutable
            ),
            (
                "DiagnosticsTests.aProvidersOwnWordsNeverReachTheReport",
                aProvidersOwnWordsNeverReachTheReport
            ),
            (
                "DiagnosticsTests.scrubbingCatchesWhatGetsInFromOutside",
                scrubbingCatchesWhatGetsInFromOutside
            ),
            (
                "DiagnosticsTests.aBugReportCanTellWhyTheBridgeFileCannotBeRead",
                aBugReportCanTellWhyTheBridgeFileCannotBeRead
            ),
            (
                "DiagnosticsTests.theReportStaysUsefulForEveryFailureWorthReporting",
                theReportStaysUsefulForEveryFailureWorthReporting
            ),
            (
                "DiagnosticsTests.theReportSaysWhatAMaintainerNeedsToKnow",
                theReportSaysWhatAMaintainerNeedsToKnow
            ),
            (
                "CapacityAlertTests.aWindowFallingBelowTenPercentIsWorthSaying",
                aWindowFallingBelowTenPercentIsWorthSaying
            ),
            (
                "CapacityAlertTests.aWindowSaysItOnceAndThenKeepsQuiet",
                aWindowSaysItOnceAndThenKeepsQuiet
            ),
            (
                "CapacityAlertTests.aWindowThatRecoversIsNewsWhenItFallsAgain",
                aWindowThatRecoversIsNewsWhenItFallsAgain
            ),
            (
                "CapacityAlertTests.aWindowThatTurnsOverIsANewWindow",
                aWindowThatTurnsOverIsANewWindow
            ),
            (
                "CapacityAlertTests.onlyAFreshReadingSpeaks",
                onlyAFreshReadingSpeaks
            ),
            (
                "CapacityAlertTests.aSilencedProviderIsSilentAndStaysCaughtUp",
                aSilencedProviderIsSilentAndStaysCaughtUp
            ),
            (
                "CapacityAlertTests.disconnectingAProviderForgetsWhatWasSaid",
                disconnectingAProviderForgetsWhatWasSaid
            ),
            (
                "CapacitySpeechTests.aWindowSaysEverythingTheCardShows",
                aWindowSaysEverythingTheCardShows
            ),
            (
                "CapacitySpeechTests.aWindowWithNoResetSaysSoRatherThanInventingOne",
                aWindowWithNoResetSaysSoRatherThanInventingOne
            ),
            (
                "CapacitySpeechTests.aProviderSaysWhoItIsAndHowItsReadingStands",
                aProviderSaysWhoItIsAndHowItsReadingStands
            ),
            (
                "CapacitySpeechTests.anUnreadableProviderSaysTheOneThingThatWouldFixIt",
                anUnreadableProviderSaysTheOneThingThatWouldFixIt
            ),
            (
                "CapacitySpeechTests.theClosedStripSaysTheWindowItIsShowing",
                theClosedStripSaysTheWindowItIsShowing
            ),
            (
                "CapacitySpeechTests.theStatesAreTellableApartWithoutColour",
                theStatesAreTellableApartWithoutColour
            ),
            (
                "PreferencesTests.nothingIsEnabledOnAnybodysBehalf",
                nothingIsEnabledOnAnybodysBehalf
            ),
            (
                "PreferencesTests.codexStartsConnectedAndClaudeDoesNot",
                codexStartsConnectedAndClaudeDoesNot
            ),
            (
                "PreferencesTests.onboardingIsOfferedOnlyToSomeoneWhoHasConnectedNothing",
                onboardingIsOfferedOnlyToSomeoneWhoHasConnectedNothing
            ),
            (
                "PreferencesTests.aDeliberateDisconnectOutlivesTheLaunchItWasMadeIn",
                aDeliberateDisconnectOutlivesTheLaunchItWasMadeIn
            ),
            (
                "PreferencesTests.aChoiceMadeAnywhereIsTheSameChoice",
                aChoiceMadeAnywhereIsTheSameChoice
            ),
            (
                "PreferencesTests.theBackgroundPaceFallsBackToTheScheduleItCameFrom",
                theBackgroundPaceFallsBackToTheScheduleItCameFrom
            ),
            (
                "CapacityArchiveTests.whatWasSeenLastComesBackAsStale",
                whatWasSeenLastComesBackAsStale
            ),
            (
                "CapacityArchiveTests.aProviderWithNothingToShowIsNotRemembered",
                aProviderWithNothingToShowIsNotRemembered
            ),
            (
                "CapacityArchiveTests.anUnreadableArchiveCostsNothing",
                anUnreadableArchiveCostsNothing
            ),
            (
                "CapacityArchiveTests.aRestartOpensOnWhatWasThereAndAsksForTheRest",
                aRestartOpensOnWhatWasThereAndAsksForTheRest
            ),
            (
                "CapacityArchiveTests.theWaitStretchesWhileAProviderIsFailing",
                theWaitStretchesWhileAProviderIsFailing
            ),
            (
                "CapacityArchiveTests.aFailureWorthRetryingIsToldFromOneThatIsNot",
                aFailureWorthRetryingIsToldFromOneThatIsNot
            ),
            (
                "PreferencesTests.theAppearanceFollowsTheMacUntilChosen",
                theAppearanceFollowsTheMacUntilChosen
            ),
            (
                "SwitchedOffTests.aProviderSwitchedOffIsNotRestoredFromTheArchive",
                aProviderSwitchedOffIsNotRestoredFromTheArchive
            ),
            (
                "SwitchedOffTests.onlyTheProvidersSwitchedOnHaveCards",
                onlyTheProvidersSwitchedOnHaveCards
            ),
            (
                "SurfacePlacementTests.theBuiltInDisplayIsTheDefaultAndOneIsAlwaysChosen",
                theBuiltInDisplayIsTheDefaultAndOneIsAlwaysChosen
            ),
            (
                "SurfacePlacementTests.aDisplayThatIsUnpluggedDoesNotStrandTheSurface",
                aDisplayThatIsUnpluggedDoesNotStrandTheSurface
            ),
            (
                "SurfacePlacementTests.aFullscreenApplicationIsToldApartFromAZoomedWindow",
                aFullscreenApplicationIsToldApartFromAZoomedWindow
            ),
            (
                "SurfacePlacementTests.onMacOS27WindowManagerHoldsWhatTheDockHeld",
                onMacOS27WindowManagerHoldsWhatTheDockHeld
            ),
            (
                "SurfacePlacementTests.aSlideBetweenFullscreenSpacesStaysFullscreen",
                aSlideBetweenFullscreenSpacesStaysFullscreen
            ),
            (
                "SurfacePlacementTests.enteringFullscreenIsToldFromTheFirstFrame",
                enteringFullscreenIsToldFromTheFirstFrame
            ),
            (
                "SurfacePlacementTests.leavingFullscreenIsToldOnceTheApplicationHasGone",
                leavingFullscreenIsToldOnceTheApplicationHasGone
            ),
            (
                "SurfacePlacementTests.aZoomedWindowOverASettledDesktopIsNotFullscreen",
                aZoomedWindowOverASettledDesktopIsNotFullscreen
            ),
            (
                "SurfacePlacementTests.aPinnedSurfaceStaysUntilItIsDismissed",
                aPinnedSurfaceStaysUntilItIsDismissed
            ),
            (
                "CapacityPaceTests.theStateIsReadOffWhatIsLeft",
                theStateIsReadOffWhatIsLeft
            ),
            (
                "CapacityPaceTests.theClockDoesNotChangeTheColour",
                theClockDoesNotChangeTheColour
            ),
            (
                "CapacityPaceTests.theHeadlineIsTheScarcestWindow",
                theHeadlineIsTheScarcestWindow
            ),
            (
                "CapacityPaceTests.theCountdownSaysHowLongInTheFewestWords",
                theCountdownSaysHowLongInTheFewestWords
            ),
            (
                "ClaudeUsageCommandTests.theUsageReportBecomesQuotaWindows",
                theUsageReportBecomesQuotaWindows
            ),
            (
                "ClaudeUsageCommandTests.proseThatNoLongerParsesIsNotAReading",
                proseThatNoLongerParsesIsNotAReading
            ),
            (
                "ClaudeUsageCommandTests.aWindowInWordingNotKnownRefusesTheWholeReport",
                aWindowInWordingNotKnownRefusesTheWholeReport
            ),
            (
                "ClaudeUsageCommandTests.windowsLeftOutOnPurposeOrNotPrintedAreNotAChangedReport",
                windowsLeftOutOnPurposeOrNotPrintedAreNotAChangedReport
            ),
            (
                "ClaudeUsageCommandTests.aWindowWithoutAYearReadsAsTheOneAhead",
                aWindowWithoutAYearReadsAsTheOneAhead
            ),
            (
                "ClaudeUsageCommandTests.theNewerOfTwoSourcesWins",
                theNewerOfTwoSourcesWins
            ),
            (
                "ClaudeUsageCommandTests.aBridgeThatWasNeverSetUpDoesNotHideWhyUsageFailed",
                aBridgeThatWasNeverSetUpDoesNotHideWhyUsageFailed
            ),
            (
                "ClaudeUsageCommandTests.aBrokenBridgeFileDoesNotHideWhyUsageFailed",
                aBrokenBridgeFileDoesNotHideWhyUsageFailed
            ),
            (
                "ClaudeUsageCommandTests.anOldReadingDoesNotHideWhyTheOtherSourceFailed",
                anOldReadingDoesNotHideWhyTheOtherSourceFailed
            ),
            (
                "ClaudeUsageCommandTests.aClaudeCodeThatHangsIsGivenUpOnAtTheTimeout",
                aClaudeCodeThatHangsIsGivenUpOnAtTheTimeout
            ),
            (
                "ClaudeUsageCommandTests.anAnswerBeforeTheTimeoutIsStillRead",
                anAnswerBeforeTheTimeoutIsStillRead
            ),
            (
                "ClaudeUsageCommandTests.askingClaudeCodeIsThrottled",
                askingClaudeCodeIsThrottled
            ),
            (
                "ClaudeUsageCommandTests.aFailedAskIsHeldOnlyBrieflyNotForTheWholeInterval",
                aFailedAskIsHeldOnlyBrieflyNotForTheWholeInterval
            ),
            (
                "UnreadCapacityTests.anUnreadSurfaceShowsNoNumbersAtAll",
                anUnreadSurfaceShowsNoNumbersAtAll
            ),
            (
                "NotchGeometryTests.theCompactSurfaceTakesItsHeightFromTheMenuBar",
                theCompactSurfaceTakesItsHeightFromTheMenuBar
            ),
            (
                "CodexAppServerProtocolTests.theSurfaceHeaderDescribesWhatItIsActuallyShowing",
                theSurfaceHeaderDescribesWhatItIsActuallyShowing
            ),
            (
                "CodexCapacityServiceTests.connectingCodexPublishesFreshCapacityFromTheAppServer",
                connectingCodexPublishesFreshCapacityFromTheAppServer
            ),
            (
                "CodexCapacityServiceTests.connectingTwiceDoesNotStartASecondAppServer",
                connectingTwiceDoesNotStartASecondAppServer
            ),
            (
                "CodexCapacityServiceTests.rollingUpdatesReachTheSurfaceWithoutReconnecting",
                rollingUpdatesReachTheSurfaceWithoutReconnecting
            ),
            (
                "CodexCapacityServiceTests.disconnectingEndsOnlyTheAppServerCapacityNotchStarted",
                disconnectingEndsOnlyTheAppServerCapacityNotchStarted
            ),
            (
                "CodexCapacityServiceTests.missingCodexProducesAnActionableDisconnectedState",
                missingCodexProducesAnActionableDisconnectedState
            ),
            (
                "CodexCapacityServiceTests.anIncompatibleCodexProducesAnActionableDisconnectedState",
                anIncompatibleCodexProducesAnActionableDisconnectedState
            ),
            (
                "CodexCapacityServiceTests.anUnauthenticatedCodexProducesAnActionableDisconnectedState",
                anUnauthenticatedCodexProducesAnActionableDisconnectedState
            ),
            (
                "CodexCapacityServiceTests.anAppServerThatStopsLeavesADisconnectedProviderNotZeroCapacity",
                anAppServerThatStopsLeavesADisconnectedProviderNotZeroCapacity
            ),
            (
                "CodexCapacityServiceTests.capacityNotchOnlyEverSendsCodexReadMethods",
                capacityNotchOnlyEverSendsCodexReadMethods
            ),
            (
                "CodexCapacityServiceTests.aClientRefusesToSendAMethodOutsideTheReadSet",
                aClientRefusesToSendAMethodOutsideTheReadSet
            ),
            (
                "CapacityNotchStoreTests.askingForTheStateAlreadyHeldAnnouncesNothing",
                askingForTheStateAlreadyHeldAnnouncesNothing
            ),
            (
                "CodexCapacityServiceTests.aFailedRefreshKeepsTheLastCapacityAsStale",
                aFailedRefreshKeepsTheLastCapacityAsStale
            ),
            (
                "CodexCapacityServiceTests.aCodexAnswerInAShapeNotKnownKeepsTheLastCapacityAndSaysWhy",
                aCodexAnswerInAShapeNotKnownKeepsTheLastCapacityAndSaysWhy
            ),
            (
                "CodexCapacityServiceTests.aFirstCodexAnswerInAShapeNotKnownSaysWhy",
                aFirstCodexAnswerInAShapeNotKnownSaysWhy
            ),
            (
                "CodexCapacityServiceTests.staleCodexCapacityKeepsTheMomentItWasRead",
                staleCodexCapacityKeepsTheMomentItWasRead
            ),
            (
                "CodexCapacityServiceTests.aCodexThatAnswersWithAnErrorSaysSoOverItsStaleCapacity",
                aCodexThatAnswersWithAnErrorSaysSoOverItsStaleCapacity
            ),
            (
                "CodexCapacityServiceTests.anAccountAnswerOutsideTheSchemaIsNotReadAsSignedOut",
                anAccountAnswerOutsideTheSchemaIsNotReadAsSignedOut
            ),
            (
                "CodexCapacityServiceTests.anAccountAnswerWithNoAccountIsSignedOutAsTheSchemaAllows",
                anAccountAnswerWithNoAccountIsSignedOutAsTheSchemaAllows
            ),
            (
                "CodexCapacityServiceTests.aFirstReadThatFailsHasNoCapacityToHold",
                aFirstReadThatFailsHasNoCapacityToHold
            ),
            (
                "LiveArchiveTests.liveArchiveReadsBackWhatTheAppWrote",
                liveArchiveReadsBackWhatTheAppWrote
            ),
            (
                "LiveClaudeUsageTests.liveClaudeUsageReportsCapacity",
                liveClaudeUsageReportsCapacity
            ),
            (
                "LiveCodexTests.liveCodexPublishesFreshCapacity",
                liveCodexPublishesFreshCapacity
            ),
            (
                "ClaudeCapacityServiceTests.connectingClaudeReadsFreshCapacityPublishedByClaudeCode",
                connectingClaudeReadsFreshCapacityPublishedByClaudeCode
            ),
            (
                "ClaudeCapacityServiceTests.anOldClaudeStatusLineReadingIsStaleCapacity",
                anOldClaudeStatusLineReadingIsStaleCapacity
            ),
            (
                "ClaudeCapacityServiceTests.aFailedClaudeBridgeRefreshKeepsTheLastCapacityAsStale",
                aFailedClaudeBridgeRefreshKeepsTheLastCapacityAsStale
            ),
            (
                "ClaudeCapacityServiceTests.publishingClaudeStatusLineWritesOnlyCapacitySnapshot",
                publishingClaudeStatusLineWritesOnlyCapacitySnapshot
            ),
            (
                "ClaudeCapacityServiceTests.fileClaudeCapacitySourceReadsPublishedQuotaWindows",
                fileClaudeCapacitySourceReadsPublishedQuotaWindows
            ),
            (
                "ClaudeCapacityServiceTests.eachWayAskingClaudeCodeFailsSaysItsOwnFix",
                eachWayAskingClaudeCodeFailsSaysItsOwnFix
            ),
            (
                "ClaudeCapacityServiceTests.aBridgeFromYesterdayDoesNotReplaceTheLastCapacityRead",
                aBridgeFromYesterdayDoesNotReplaceTheLastCapacityRead
            ),
            (
                "ClaudeCapacityServiceTests.missingClaudeStatusLineSnapshotIsActionableAndDisconnected",
                missingClaudeStatusLineSnapshotIsActionableAndDisconnected
            ),
            (
                "ClaudeCapacityServiceTests.disconnectingClaudeClearsFreshCapacityFromTheSurface",
                disconnectingClaudeClearsFreshCapacityFromTheSurface
            ),
            (
                "MusicTests.theSpeakerIsStruckThroughWhenNothingIsHeard",
                theSpeakerIsStruckThroughWhenNothingIsHeard
            ),
            (
                "MusicTests.mutingEmptiesTheBarAndKeepsTheLevel",
                mutingEmptiesTheBarAndKeepsTheLevel
            ),
            (
                "MusicTests.aFullLineFromTheAdapterSaysWhatIsPlaying",
                aFullLineFromTheAdapterSaysWhatIsPlaying
            ),
            (
                "MusicTests.aDiffLineUpdatesTheLastFullOne",
                aDiffLineUpdatesTheLastFullOne
            ),
            (
                "MusicTests.theArtworkOutlivesAFullLineForTheSameTrackOnly",
                theArtworkOutlivesAFullLineForTheSameTrackOnly
            ),
            (
                "MusicTests.aMusicModuleThatCannotReadSaysSoInTheReport",
                aMusicModuleThatCannotReadSaysSoInTheReport
            ),
            (
                "MusicTests.eachControlIsTheCommandTheAdapterExpects",
                eachControlIsTheCommandTheAdapterExpects
            ),
            (
                "MusicTests.thePositionMovesOnFromWhenItWasReported",
                thePositionMovesOnFromWhenItWasReported
            ),
            (
                "MusicTests.aLineTheAdapterDidNotWriteIsNotAReading",
                aLineTheAdapterDidNotWriteIsNotAReading
            ),
            (
                "MusicTests.theRowShowsWhilePlayingAndLingersBrieflyOnPause",
                theRowShowsWhilePlayingAndLingersBrieflyOnPause
            ),
            (
                "MusicTests.nothingPlayingOrUnreadableShowsNoRow",
                nothingPlayingOrUnreadableShowsNoRow
            ),
        ]
        let selection = CommandLine.arguments.dropFirst().first
        let selected = tests.filter { selection == nil || $0.0 == selection }

        guard !selected.isEmpty else {
            print("No test matched \(selection ?? "")")
            exit(2)
        }

        var failures = 0
        for (name, test) in selected {
            do {
                try await test()
                print("PASS \(name)")
            } catch {
                failures += 1
                print("FAIL \(name): \(error)")
            }
        }

        exit(failures == 0 ? 0 : 1)
    }
}
