//! What the Shelf takes from the clipboard, and what it never does (ADR 0005,
//! amended). The rules are written against the type identifiers the macOS
//! pasteboard uses (`public.png`, `public.file-url`, …); a platform adapter
//! maps its own formats onto them (`canonical`), so the rules are the same
//! everywhere and the data they are fed is the platform's.

use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;
use std::path::Path;

/// Where the rules are for: only the lists of names differ.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Platform {
    MacOs,
    Linux,
}

impl Platform {
    pub fn current() -> Platform {
        if cfg!(target_os = "macos") {
            Platform::MacOs
        } else {
            Platform::Linux
        }
    }
}

/// The data the intake rules are fed: which markers say a copy is secret,
/// which applications are never read from, and which are file managers (where
/// copying a file is a file operation and not a thing to keep at hand).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ClipboardRules {
    pub secret_markers: BTreeSet<String>,
    pub excluded_applications: BTreeSet<String>,
    pub file_managers: BTreeSet<String>,
}

fn set(items: &[&str]) -> BTreeSet<String> {
    items.iter().map(|s| s.to_string()).collect()
}

impl ClipboardRules {
    /// The nspasteboard.org markers, and the older ones listed there, for what
    /// must not be kept; Apple's own password apps, which mark nothing they
    /// copy; and Finder.
    pub fn macos() -> Self {
        Self {
            secret_markers: set(&[
                "org.nspasteboard.ConcealedType",
                "org.nspasteboard.TransientType",
                "org.nspasteboard.AutoGeneratedType",
                "de.petermaurer.TransientPasteboardType",
                "com.agilebits.onepassword",
                "Pasteboard generator type",
                "com.typeit4me.clipping",
            ]),
            excluded_applications: set(&["com.apple.Passwords", "com.apple.keychainaccess"]),
            file_managers: set(&["com.apple.finder"]),
        }
    }

    /// KDE's `x-kde-passwordManagerHint` (KeePassXC, Bitwarden and others set
    /// it to `secret`) stands for the nspasteboard markers; Linux has no
    /// system password app that marks nothing, so applications are named by
    /// their desktop-file ids and are the person's to add besides.
    pub fn linux() -> Self {
        let mut markers = Self::macos().secret_markers;
        markers.insert("x-kde-passwordManagerHint".into());
        Self {
            secret_markers: markers,
            excluded_applications: set(&[
                "org.keepassxc.KeePassXC",
                "com.bitwarden.desktop",
                "com.1password.1Password",
                "org.gnome.seahorse.Application",
                "org.gnome.World.Secrets",
                "app.drey.KeyRack",
            ]),
            file_managers: set(&["org.gnome.Nautilus", "org.kde.dolphin", "org.xfce.Thunar", "nemo", "pcmanfm", "pcmanfm-qt"]),
        }
    }

    pub fn for_platform(platform: Platform) -> Self {
        match platform {
            Platform::MacOs => Self::macos(),
            Platform::Linux => Self::linux(),
        }
    }

    pub fn current() -> Self {
        Self::for_platform(Platform::current())
    }

    /// Passwords and Keychain Access mark nothing they copy, so nothing is
    /// read while one of them — or any application the platform names — is in
    /// front.
    pub fn is_excluded_application(&self, application: Option<&str>) -> bool {
        application.is_some_and(|a| self.excluded_applications.contains(a))
    }

    pub fn is_file_manager(&self, application: Option<&str>) -> bool {
        application.is_some_and(|a| self.file_managers.contains(a))
    }

    pub fn has_secret_marker(&self, types: &BTreeSet<&str>) -> bool {
        types.iter().any(|t| self.secret_markers.contains(*t))
    }
}

impl Default for ClipboardRules {
    /// The macOS rules, which are the reference.
    fn default() -> Self {
        Self::macos()
    }
}

/// A screenshot taken to the clipboard, which the Shelf takes in when asked to
/// (ADR 0005, amended). macOS puts a screenshot there as one item holding PNG
/// and nothing else; an image copied from a page or an application comes with
/// more — TIFF, a link, an archive of the page.
pub struct ScreenshotClipboard;

/// The language a screenshot is named in. The caller resolves "system".
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum NameLanguage {
    English,
    Russian,
}

impl ScreenshotClipboard {
    /// `items`: each pasteboard item's type identifiers.
    pub fn is_screenshot(items: &[Vec<String>]) -> bool {
        items.len() == 1 && items[0].len() == 1 && items[0][0] == "public.png"
    }

    /// As macOS names a screenshot saved to a file: "Снимок экрана 2026-10-01
    /// в 01.02.03.png". `at` is the moment in the zone it is named in.
    pub fn name<Tz: chrono::TimeZone>(at: &chrono::DateTime<Tz>, language: NameLanguage) -> String
    where
        Tz::Offset: std::fmt::Display,
    {
        let day = at.format("%Y-%m-%d");
        let time = at.format("%H.%M.%S");
        match language {
            NameLanguage::Russian => format!("Снимок экрана {day} в {time}.png"),
            NameLanguage::English => format!("Screenshot {day} at {time}.png"),
        }
    }

    /// What names an image taken from the clipboard that is not a screenshot:
    /// "Image 2026-10-01 at 01.02.03" and its extension, from the screenshot
    /// name's date and time.
    pub fn image_name<Tz: chrono::TimeZone>(at: &chrono::DateTime<Tz>, language: NameLanguage, extension: &str) -> String
    where
        Tz::Offset: std::fmt::Display,
    {
        let name = Self::name(at, language);
        // The date and time: from the first digit, without ".png".
        let stamp: String = name.chars().skip_while(|c| !c.is_numeric()).collect();
        let stamp = &stamp[..stamp.len() - 4];
        let label = match language {
            NameLanguage::Russian => "Изображение",
            NameLanguage::English => "Image",
        };
        format!("{label} {stamp}.{extension}")
    }
}

/// What the Shelf takes from the clipboard when asked to (ADR 0005, amended):
/// a screenshot, an image copied from a page or an application, or a file
/// copied in another application — media or a document from a messenger, an
/// attachment from mail. Never text, never anything a password manager marks
/// as secret, and nothing copied in a file manager, where copying a file is a
/// file operation and not a thing to keep at hand.
pub struct ClipboardTake;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "choice", content = "type", rename_all = "camelCase")]
pub enum Choice {
    Nothing,
    /// A lone PNG: a screenshot, named as macOS names one.
    Screenshot,
    /// An image copied as data, in this type.
    Data(String),
    /// A copied file, read into memory: it may sit in another application's
    /// cache, which can be emptied.
    FileIntoMemory,
    /// A copied file too large to hold in memory, kept as a reference.
    FileReference,
}

impl ClipboardTake {
    /// Up to this size a copied file is read into memory.
    pub const MEMORY_LIMIT: u64 = 50 * 1024 * 1024;

    /// Image types, in the order they are preferred: the ones that keep the
    /// image as it was, TIFF — a converted copy — last.
    pub const IMAGE_TYPES: [&'static str; 6] =
        ["public.png", "public.jpeg", "org.webmproject.webp", "public.heic", "com.compuserve.gif", "public.tiff"];

    /// - `items`: each pasteboard item's type identifiers.
    /// - `file_path`: the file the clipboard points at, when it holds one.
    /// - `from_file_manager`: a file manager was in front when it was copied.
    pub fn choose(
        items: &[Vec<String>],
        file_path: Option<&Path>,
        file_size: Option<u64>,
        is_directory: bool,
        from_file_manager: bool,
        rules: &ClipboardRules,
    ) -> Choice {
        let types: BTreeSet<&str> = items.iter().flatten().map(String::as_str).collect();
        if types.is_empty() || rules.has_secret_marker(&types) {
            return Choice::Nothing;
        }
        if types.contains("public.file-url") {
            if file_path.is_none() || from_file_manager || is_directory {
                return Choice::Nothing;
            }
            return if file_size.unwrap_or(0) <= Self::MEMORY_LIMIT { Choice::FileIntoMemory } else { Choice::FileReference };
        }
        if ScreenshotClipboard::is_screenshot(items) {
            return Choice::Screenshot;
        }
        match Self::IMAGE_TYPES.iter().find(|t| types.contains(**t)) {
            Some(kind) => Choice::Data((*kind).to_owned()),
            None => Choice::Nothing,
        }
    }

    /// The file name extension for an image type, as the type's preferred
    /// extension.
    pub fn extension_for(image_type: &str) -> &'static str {
        match image_type {
            "public.png" => "png",
            "public.jpeg" => "jpeg",
            "org.webmproject.webp" => "webp",
            "public.heic" => "heic",
            "com.compuserve.gif" => "gif",
            "public.tiff" => "tiff",
            _ => "png",
        }
    }
}

/// Whether a text on the clipboard is kept as a Clipping (ADR 0005): plain
/// text, not a copied file's name, nothing a password manager marks, nothing
/// copied while Passwords, Keychain Access or a chosen application is in front,
/// and nothing CapaTheNotch put there itself — whether it wrote it, or someone
/// pressed ⌘C in one of its windows.
pub struct ClipboardText;

impl ClipboardText {
    /// The type CapaTheNotch adds to everything it puts on the clipboard, so
    /// that its own copies are never kept. A platform that cannot add a type
    /// of that name adds its own and reports it as this one (`canonical`).
    pub const OWN_MARKER: &'static str = "app.capacitynotch.own";

    const TEXT_TYPES: [&'static str; 2] = ["public.utf8-plain-text", "public.plain-text"];

    /// - `types`: each pasteboard item's type identifiers.
    /// - `frontmost`: the application in front when it was copied; the system
    ///   does not say which one wrote it.
    /// - `excluded`: the applications chosen in Settings.
    /// - `own_application`: CapaTheNotch's own identifier; one ending in a dot
    ///   names its family (`tech.capathenotch.`: its Settings, its drop window).
    pub fn is_kept(
        types: &[Vec<String>],
        frontmost: Option<&str>,
        excluded: &BTreeSet<String>,
        own_application: Option<&str>,
        rules: &ClipboardRules,
    ) -> bool {
        let all: BTreeSet<&str> = types.iter().flatten().map(String::as_str).collect();
        if !Self::TEXT_TYPES.iter().any(|t| all.contains(t))
            || all.contains("public.file-url")
            || all.contains(Self::OWN_MARKER)
            || rules.has_secret_marker(&all)
        {
            return false;
        }
        if rules.is_excluded_application(frontmost) {
            return false;
        }
        if let Some(front) = frontmost {
            if excluded.contains(front) || own_application.is_some_and(|own| is_own(front, own)) {
                return false;
            }
        }
        true
    }
}

/// Whether `front` is CapaTheNotch itself: its identifier, or, for one ending in
/// a dot, any under it.
fn is_own(front: &str, own: &str) -> bool {
    front == own || own.ends_with('.') && front.starts_with(own)
}

/// Maps a platform's clipboard formats onto the identifiers the rules read.
/// Anything not listed passes through unchanged, so a secret marker a platform
/// reports under its own name is still found by `ClipboardRules`.
pub mod canonical {
    /// X11 / Wayland MIME types and the targets clients offer.
    pub fn linux(mime: &str) -> String {
        let bare = mime.split(';').next().unwrap_or(mime).trim();
        match bare {
            "text/plain" | "UTF8_STRING" | "STRING" | "TEXT" => "public.utf8-plain-text".into(),
            "text/html" => "public.html".into(),
            "image/png" => "public.png".into(),
            "image/jpeg" => "public.jpeg".into(),
            "image/webp" => "org.webmproject.webp".into(),
            "image/heic" | "image/heif" => "public.heic".into(),
            "image/gif" => "com.compuserve.gif".into(),
            "image/tiff" => "public.tiff".into(),
            // A copied file: GNOME and KDE both offer the list of URIs.
            "text/uri-list" | "x-special/gnome-copied-files" | "application/x-kde-cutselection" => "public.file-url".into(),
            "application/x-capacitynotch-own" => super::ClipboardText::OWN_MARKER.into(),
            _ => mime.into(),
        }
    }
}
