#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Ticket 30: CapaTheNotch is signed with the author's own self-signed
# certificate, so only a build the author signed inherits what macOS granted.
# The author runs this once. It never reads, prints or exports the private key:
# the export in stage 4 is done by hand in Keychain Access.

TOTAL_STAGES=4

CERT_NAME="CapaTheNotch"
VALIDITY_DAYS=7300
project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$project_root/.signing.env"

# The SHA-1 of every code-signing identity (certificate with its private key)
# in the login keychain whose name is exactly CERT_NAME. Untrusted ones too:
# a self-signed root is untrusted, and codesign signs with it all the same.
identity_hashes() {
  security find-identity -p codesigning "$HOME/Library/Keychains/login.keychain-db" 2>/dev/null \
    | awk -v name="\"${CERT_NAME}\"" '$1 ~ /^[0-9]+\)$/ && index($0, name) { print $2 }' \
    | sort -u
}

banner "CapaTheNotch: свой сертификат для подписи"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Создать сертификат"
if [[ -n "$(identity_hashes)" ]]; then
  say "Сертификат «${CERT_NAME}» с ключом уже есть в связке «login», создавать не нужно."
  pause "Enter: дальше"
else
  say "Сертификат и его закрытый ключ создаёт macOS, в вашей связке «login»."
  say "Сейчас откроется «Связка ключей» (Keychain Access)."
  open -a "Keychain Access" || warn "не открылась: Finder ▸ Программы ▸ Утилиты ▸ Связка ключей"
  step "Меню «Связка ключей» ▸ «Ассистент сертификации» ▸ «Создать сертификат…»"
  note "  (Keychain Access ▸ Certificate Assistant ▸ Create a Certificate…)"
  step "Имя: ${CERT_NAME}"
  step "Тип идентификации: «Самоподписанный корневой» (Self-Signed Root)"
  step "Тип сертификата: «Подпись кода» (Code Signing)"
  step "Поставьте галочку «Переопределить настройки по умолчанию» (Let me override defaults) ▸ Продолжить"
  step "Предупреждение о самоподписанном сертификате ▸ Продолжить"
  step "Период действия (дней): ${VALIDITY_DAYS} — двадцать лет. Остальное на этом экране не трогайте"
  step "Сведения о сертификате: имя ${CERT_NAME}. Сотрите e-mail, если Ассистент его подставил,"
  note "  и оставьте пустыми организацию, отдел, город — всё, кроме имени и страны"
  warn "сертификат лежит внутри каждой сборки: всё, что здесь останется, увидит любой"
  step "Ключ (2048 бит, RSA), «Использование ключа», «Расширенное использование» с «Подписью кода»,"
  note "  основные ограничения, альтернативное имя — оставьте как есть, Продолжить"
  step "Связка ключей: «login» (вход) ▸ Создать ▸ Готово"
  note "Если какой-то экран выглядит иначе — оставьте его по умолчанию и напишите Claude."
  pause "Enter, когда сертификат создан"
  until [[ -n "$(identity_hashes)" ]]; do
    warn "в связке «login» не нашлось сертификата для подписи кода с именем ровно «${CERT_NAME}»."
    note "Проверьте имя и тип «Подпись кода» в «Мои сертификаты»."
    pause "Enter: проверить ещё раз (Ctrl-C — выйти)"
  done
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Проверить сертификат"
hashes="$(identity_hashes)"
if (( $(printf '%s\n' "$hashes" | wc -l) > 1 )); then
  warn "сертификатов «${CERT_NAME}» с ключом несколько:"
  printf '%s\n' "$hashes" | while read -r h; do note "  $h"; done
  warn "ничего не удаляйте сами: остановитесь здесь и напишите Claude, какой из них нужен."
  exit 1
fi
CAPACITY_NOTCH_SIGNING_IDENTITY="$hashes"
say "SHA-1: ${CAPACITY_NOTCH_SIGNING_IDENTITY}"
# The certificate with exactly this SHA-1: -c alone matches any name that
# contains CERT_NAME and takes the first.
details="$(security find-certificate -a -c "${CERT_NAME}" -Z -p "$HOME/Library/Keychains/login.keychain-db" \
  | awk -v hash="${CAPACITY_NOTCH_SIGNING_IDENTITY}" '/^SHA-1 hash:/ { mine = ($3 == hash); next } mine' \
  | openssl x509 -noout -subject -enddate -ext extendedKeyUsage 2>/dev/null || true)"
printf '%s\n' "$details" | sed 's/^/    /'
if ! grep -q "Code Signing" <<<"$details"; then
  warn "в сертификате нет «Подписи кода» (Code Signing): удалите его в «Связке ключей» и пройдите этап 1 снова."
  exit 1
fi
say ""
say "Теперь пробная подпись временного файла."
warn "macOS спросит, можно ли codesign подписывать ключом «${CERT_NAME}»:"
step "введите пароль входа и нажмите «Всегда разрешать» (Always Allow)"
note "Тогда сборки будут подписываться без этого вопроса."
pause "Enter: подписать"
scratch="$(mktemp -d)"
trap 'rm -rf "$scratch"' EXIT
cp /usr/bin/true "$scratch/probe"
until codesign --force --sign "${CAPACITY_NOTCH_SIGNING_IDENTITY}" --timestamp=none "$scratch/probe" 2>"$scratch/error"; do
  warn "подпись не вышла: $(cat "$scratch/error")"
  note "Если окно было — нажмите «Всегда разрешать», не «Разрешить» и не «Запретить»."
  pause "Enter: попробовать ещё раз (Ctrl-C — выйти)"
done
printf '  %s✓ подписано%s %s\n' "$GREEN" "$RESET" "$(codesign -dvv "$scratch/probe" 2>&1 | grep '^Authority=')"
rm -rf "$scratch"
pause "Enter: дальше"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Сказать сборке, чем подписывать"
say "Скрипты сборки берут сертификат по SHA-1 из .signing.env (его нет в git)"
say "или из переменной окружения CAPACITY_NOTCH_SIGNING_IDENTITY."
note "SHA-1 — не секрет: он попадёт в README, чтобы любой мог сверить подпись."
write_env CAPACITY_NOTCH_SIGNING_IDENTITY "${CAPACITY_NOTCH_SIGNING_IDENTITY}"
pause "Enter: дальше"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Резервная копия ключа"
say "Если закрытый ключ пропадёт, следующая сборка будет для macOS новым"
say "приложением, и всем придётся выдавать разрешения заново. Копию — в менеджер паролей."
open -a "Keychain Access" || true
step "В менеджере паролей создайте запись «CapaTheNotch — ключ подписи» и сгенерируйте длинный пароль"
step "«Связка ключей» ▸ «login» ▸ вкладка «Мои сертификаты» ▸ правый клик по «${CERT_NAME}» ▸ «Экспортировать…»"
step "Формат: «Файл обмена личной информацией (.p12)», сохраните на Рабочий стол"
step "Введите пароль из менеджера паролей, затем пароль входа, чтобы macOS отдала ключ"
step "Приложите .p12 к записи в менеджере паролей"
step "Удалите .p12 с Рабочего стола и очистите Корзину"
warn "никогда не кладите .p12 в папку проекта и никому его не отправляйте."
pause "Enter, когда копия в менеджере паролей"
leftovers=()
while IFS= read -r -d '' f; do leftovers+=("$f"); done \
  < <(find "$HOME/Desktop" "$HOME/Downloads" "$project_root" -maxdepth 2 -name '*.p12' -print0 2>/dev/null)
if (( ${#leftovers[@]} )); then
  warn "ещё лежат файлы .p12 — удалите их, если копия уже в менеджере паролей:"
  for f in "${leftovers[@]}"; do note "  $f"; done
  SKIPPED+=("удалить .p12: ${leftovers[*]}")
fi
confirm "Копия ключа с паролем лежит в менеджере паролей?" \
  || SKIPPED+=("резервная копия ключа в менеджере паролей (этап 4)")

finish
say "Сертификат: ${CERT_NAME}, SHA-1 ${CAPACITY_NOTCH_SIGNING_IDENTITY}"
say "Напишите Claude, что мастер пройден."
printf '\n'
