#!/usr/bin/env python3
"""Writes src/geist_widths.rs: Geist Medium (wght 500) advance widths and pair
kerning, in 1/1000 em, for the characters a Script is likely to hold. Needs fontTools:

    python3 -m venv v && v/bin/pip install fonttools
    v/bin/python linux/crates/teleprompter/tools/gen_geist_widths.py

The kerning is the font's GPOS `kern` feature, flattened over those characters
and folded into classes: characters whose kerning on the left (or the right) is
the same share a class, and a matrix holds a value for each pair of classes.
Class 0 kerns with nothing.
"""
import os
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

root = os.path.join(os.path.dirname(__file__), "..", "..", "..", "..")
font = TTFont(os.path.join(root, "Sources/CapacityNotch/Resources/Geist.ttf"))
font = instantiateVariableFont(font, {"wght": 500}, inplace=False)
upm = font["head"].unitsPerEm
cmap = font.getBestCmap()
hmtx = font["hmtx"]

ranges = [(0x20, 0x7E), (0xA0, 0xFF), (0x2D0, 0x2DD), (0x400, 0x4FF), (0x2010, 0x2027), (0x2030, 0x203A), (0x2116, 0x2116), (0x2190, 0x2193)]
cps = [cp for lo, hi in ranges for cp in range(lo, hi + 1) if cp in cmap]
notdef = round(hmtx[".notdef"][0] * 1000 / upm)
advances = {cp: round(hmtx[cmap[cp]][0] * 1000 / upm) for cp in cps}
space = advances.get(0x20, 250)


def pair_value(lookup, left, right):
    """What one PairPos lookup adds to `left`'s advance before `right`, or None
    when none of its subtables applies (and HarfBuzz tries the next)."""
    for sub in lookup.SubTable:
        if lookup.LookupType == 9:
            sub = sub.ExtSubTable
        coverage = sub.Coverage.glyphs
        if left not in coverage:
            continue
        if sub.Format == 1:
            for record in sub.PairSet[coverage.index(left)].PairValueRecord:
                if record.SecondGlyph == right:
                    return getattr(record.Value1, "XAdvance", 0) or 0
        else:
            first = sub.ClassDef1.classDefs.get(left, 0)
            second = sub.ClassDef2.classDefs.get(right, 0)
            return getattr(sub.Class1Record[first].Class2Record[second].Value1, "XAdvance", 0) or 0
    return None


gpos = font["GPOS"].table
kern_lookups = sorted({i for record in gpos.FeatureList.FeatureRecord if record.FeatureTag == "kern" for i in record.Feature.LookupListIndex})
lookups = [gpos.LookupList.Lookup[i] for i in kern_lookups]
kerning = {}
for a in cps:
    for b in cps:
        total = sum(v for v in (pair_value(lookup, cmap[a], cmap[b]) for lookup in lookups) if v)
        if total:
            kerning[(a, b)] = round(total * 1000 / upm)


def classes(key):
    """Numbers each distinct row (or column) of the kerning, the empty one 0."""
    numbered, of = {(0,) * len(cps): 0}, {}
    for cp in cps:
        of[cp] = numbered.setdefault(key(cp), len(numbered))
    return of, [k for k, _ in sorted(numbered.items(), key=lambda item: item[1])]


left_of, left_rows = classes(lambda a: tuple(kerning.get((a, b), 0) for b in cps))
right_of, _ = classes(lambda b: tuple(kerning.get((a, b), 0) for a in cps))
right_count = max(right_of.values()) + 1
matrix = [[0] * right_count for _ in left_rows]
for (a, b), value in kerning.items():
    matrix[left_of[a]][right_of[b]] = value
assert len(left_rows) < 256 and right_count < 256

out = os.path.join(os.path.dirname(__file__), "..", "src", "geist_widths.rs")
with open(out, "w") as f:
    f.write("// Generated by tools/gen_geist_widths.py from Geist.ttf at weight 500. Do not edit.\n\n")
    f.write("/// `(code point, advance in 1/1000 em, left kerning class, right kerning class)`, sorted by code point.\n")
    f.write("pub(crate) const ADVANCES: &[(u32, u16, u8, u8)] = &[\n")
    rows = [(cp, advances[cp], left_of[cp], right_of[cp]) for cp in cps]
    for i in range(0, len(rows), 6):
        f.write("    " + " ".join(f"({cp:#x}, {w}, {l}, {r})," for cp, w, l, r in rows[i:i + 6]) + "\n")
    f.write("];\n\n")
    f.write(f"/// Right kerning classes: a row of `KERNING`.\npub(crate) const RIGHT_CLASSES: usize = {right_count};\n\n")
    f.write("/// The `kern` feature's pair adjustments in 1/1000 em, `[left class * RIGHT_CLASSES + right class]`.\n")
    f.write("pub(crate) const KERNING: &[i16] = &[\n")
    for row in matrix:
        for i in range(0, len(row), 20):
            f.write("    " + " ".join(f"{v}," for v in row[i:i + 20]) + "\n")
    f.write("];\n\n")
    f.write(f"/// What a character the table lacks is given: the font's own `.notdef`.\npub(crate) const FALLBACK: u16 = {notdef};\n")
    f.write(f"pub(crate) const SPACE: u16 = {space};\n")
print(len(rows), "advances,", len(kerning), "kerning pairs in", len(left_rows), "x", right_count, "classes ->", out)
